# Generated by Django 6.0.2 on 2026-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futrruser',
            name='isPreboarded',
            field=models.BooleanField(default=False),
        ),
    ]
