# Generated by Django 6.0.2 on 2026-03-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_reset_and_2fa'),
        ('users', '0002_futrruser_ispreboarded'),
    ]

    operations = [
    ]
