# Generated by Django 6.0.2 on 2026-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260304_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futrruser',
            name='capsules_sealed',
        ),
        migrations.RemoveField(
            model_name='futrruser',
            name='capsules_unlocked',
        ),
    ]
