# Generated by Django 6.0.2 on 2026-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_followrequest_futrruser_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
