# Generated by Django 6.0.2 on 2026-04-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_supportticket_userquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futrruser',
            name='notify_capsule_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futrruser',
            name='notify_capsule_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futrruser',
            name='notify_capsule_unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futrruser',
            name='notify_friend_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='futrruser',
            name='notify_nearby_capsule',
            field=models.BooleanField(default=True),
        ),
    ]
