# Generated by Django 6.0.2 on 2026-04-01 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_users_email_status_d2e3f4_idx_users_email_status_8f6ac0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('free+', 'Free+'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_capsules_per_week', models.PositiveIntegerField(default=5)),
                ('max_events_per_week', models.PositiveIntegerField(default=1)),
                ('max_event_participants', models.PositiveIntegerField(default=200)),
                ('max_recipients_per_capsule', models.PositiveIntegerField(default=5)),
                ('max_media_per_capsule', models.PositiveIntegerField(default=10)),
                ('atlas_radius_miles', models.FloatField(default=1.0)),
                ('atlas_radius_growth', models.FloatField(default=0.5)),
                ('max_storage_mb', models.PositiveIntegerField(default=100)),
                ('max_favorites', models.PositiveIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
