# Generated by Django 6.0.2 on 2026-04-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscription_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='users_email_status_8f6ac0_idx',
            old_name='users_email_status_d2e3f4_idx',
        ),
    ]
