# Generated by Django 6.0.2 on 2026-04-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscription_model'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE indexname = 'users_email_status_d2e3f4_idx'
                ) THEN
                    ALTER INDEX users_email_status_d2e3f4_idx
                    RENAME TO users_email_status_8f6ac0_idx;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
