# Generated by Django 6.0.2 on 2026-03-15 18:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sealed', 'Sealed'), ('unlocked', 'Unlocked'), ('expired', 'Expired'), ('broken', 'Broken')], default='sealed', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unlock_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('unlock_radius_meters', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsules_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text Note'), ('photo', 'Photo'), ('voice', 'Voice Note'), ('video', 'Video')], max_length=10)),
                ('body', models.TextField(blank=True)),
                ('file', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.capsule')),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleEncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('umk', 'User Maintained Key'), ('smk', 'System Maintained Key')], max_length=10)),
                ('encrypted_cek', models.BinaryField()),
                ('kek_nonce', models.BinaryField()),
                ('key_verifier', models.BinaryField(blank=True, null=True)),
                ('kdf_salt', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to='app.capsule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encryption_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapsuleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('added_via', models.CharField(choices=[('invited', 'Invited'), ('link', 'Link'), ('public', 'Public')], default='invited', max_length=20)),
                ('has_opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_recipients', to='app.capsule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('capsule', 'email'), ('capsule', 'user')},
            },
        ),
        migrations.AddField(
            model_name='capsule',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='capsules_received', through='app.CapsuleRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unlock_at', models.DateTimeField()),
                ('invite_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='capsule',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsules', to='app.event'),
        ),
    ]
