# Generated by Django 6.0.2 on 2026-03-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_capsule_created_at_alter_capsule_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='passphrase_hint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
