# Generated by Django 6.0.2 on 2026-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
