# Generated by Django 6.0.2 on 2026-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_capsule_listed_in_atlas_capsulepin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('capsule_unlocked', 'Capsule Unlocked'), ('recipient_added', 'Added as Recipient'), ('follow_request', 'Follow Request'), ('event_joined', 'Someone Joined Your Event'), ('event_unlocked', 'Event Capsules Unlocked'), ('system', 'System')], max_length=30),
        ),
    ]
