# Generated by Django 6.0.2 on 2026-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_follow_request_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('graduation', 'Graduation'), ('anniversary', 'Anniversary'), ('new_year', 'New Year'), ('sports', 'Sports'), ('travel', 'Travel'), ('festival', 'Festival'), ('music', 'Music'), ('milestone', 'Milestone'), ('reunion', 'Reunion'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
